CREATE TABLE [dbo].[Pipline] (
    [Id] BIGINT IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (100) NULL,
    [SourceTypeId] INT NULL,
    [SourseConnection] nvarchar(max),
    [SourseCredentials] nvarchar(max),
    [SourceTypeSettingsJson] nvarchar(max),
    [IsEnabled] BIT NULL,
    [LastProcessedAt] DATETIME2 (7)  NULL,
    [ActualRowVersion] VARBINARY(8) NULL,
    [PrimaryKeyIsUsed] BIT NULL,
    [PrimaryKeySchemeJson] NVARCHAR (MAX) NULL,
    [VersioningIsUsed] BIT NULL,
    [VersioningSchemeJson] NVARCHAR (MAX) NULL,
    [TransferToFlatTableIsEnabled] BIT NULL,
    [TransferToFlatTableSchemeJson] NVARCHAR (MAX) NULL,
    [LastProcessedStatus] NVARCHAR(MAX),
    [BatchSize] INT NOT NULL CONSTRAINT [DF_Pipline_BatchSize] DEFAULT (100000),
    [CurrentRow] INT NOT NULL CONSTRAINT [DF_Pipline_CurrentRow] DEFAULT (0),
    CONSTRAINT [PK_Pipline] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [AK_Pipline] UNIQUE([Name]),   
    CONSTRAINT [FK_SourceType] FOREIGN KEY ([SourceTypeId]) REFERENCES [dbo].[SourceType] ([Id])
);